pub mod format;
pub mod backends;

pub mod ast;
pub mod bytecode;
pub mod docgen;
pub mod aot;
pub mod type_metadata;
pub mod effect_checker;
pub mod hir;
pub mod hir_lower;
pub mod integration_tests;
pub mod lexer;
#[cfg(feature = "lsp")]
pub mod lsp;
pub mod mir;
pub mod mir_codegen;
#[cfg(feature = "wasm-backend")]
pub mod mir_wasm;
#[cfg(feature = "wasm-backend")]
pub mod wasm_runtime;
pub mod wasm_types;
#[cfg(feature = "wasm-backend")]
pub mod wasm_component_runtime;
pub mod mir_lower;
pub mod package;
pub mod parser;
pub mod repl;
pub mod stdlib;
pub mod typechecker;
pub mod types;
pub mod type_ir;
pub mod value_layout;
pub mod vm;

pub mod jit;
pub mod runtime;
pub mod ai;
pub mod ffi;
#[cfg(feature = "python")]
pub mod python;
#[cfg(test)]
pub mod stress_tests;
